require:
  - rubocop-ast
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - db/migration/**/*

